---
timezone: UTC
title: Paul Hershey
email: hersheypaul@gmail.com

description: 'I am a UX designer based in Orlando, FL focusing on product design and user research.'

url:
twitter:
  username: paulhershey
  card: summary
social:
  links:
    - https://twitter.com/paulhershey
    - https://www.facebook.com/phershey
    - https://www.linkedin.com/in/paulhershey/
    - https://plus.google.com/u/1/+PaulHershey
    - https://github.com/paulhershey
    - https://dribbble.com/paulhershey
    - https://www.behance.net/paulhershey
baseurl: /
cloudinary: https://res.cloudinary.com/paulhershey
collections:
  pages:
    output: true
    permalink: "/:path/"
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    title: ''
    description: ''
    image:
      name: ''
      path: 'img/home/lg/PaulHershey.png'
      width: ''
      height: ''
plugins:
- jekyll-sitemap
- jekyll-seo-tag
permalink: "/articles/:title/"

highlighter: rouge
markdown: kramdown
